spring.application.name=GeneratorFaktur
server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://dpg-d7jo8o67r5hc73barn3g-a.frankfurt-postgres.render.com:5432/useremails_11ae?sslmode=require
spring.datasource.username=useremails_11ae_user
spring.datasource.password=lydv6WDCB9gJu1RRtckmNhoFIZolqyQi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect