spring.application.name=GeneratorFaktur
server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://ep-proud-leaf-alwnsglc-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_AWcvDTaOj57B

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=whsec_b7803146d4db85ec859f726428f3c243383741900d72889aa283b645209f66e8
